### ISSUE TITLE
Compilation error with crystal 0.25.0

### ISSUE THREAD

**Issue by imdrasil** [imdrasil/jennifer.cr#145]
ATM I work on providing support of crystal `0.25.0`. This process has some challenges but the most interesting one has changed type fallback system and/or method return type eager checking. As an example
after running `crystal spec/view/experimental_mapping_spec.cr` on the `add_crystal_25_support` branch we will get: 
```
Module validation failed: Stored value type does not match pointer operand type!
  store %"Jennifer::QueryBuilder::MultiQueryRelationTree"* %1, %"Jennifer::QueryBuilder::NestedRelationTree"** %__temp_1884
 %"Jennifer::QueryBuilder::NestedRelationTree"*Stored value type does not match pointer operand type!
  store %"Jennifer::QueryBuilder::NestedRelationTree"* %4, %"Jennifer::QueryBuilder::MultiQueryRelationTree"** %5
 %"Jennifer::QueryBuilder::MultiQueryRelationTree"*
???
...
```
This is actually isn't the only problem, but ATM at least we need to figure out how to fix this simplest example

**Comment by imdrasil** [comment]
I found all the places and fixed almost all of them. Tomorrow `v0.6.0` branch will get a PR with hotfixes. During this week I'm going to make a v0.6.0 release - `v0.6.0` branch got too much new functionality so we can't wait more time.

**Comment by imdrasil** [comment]
Closed by #146
